# Generated by Django 5.1.5 on 2025-01-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_toddler'),
    ]

    operations = [
        migrations.AddField(
            model_name='toddler',
            name='address',
            field=models.TextField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toddler',
            name='contact_number',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toddler',
            name='full_name',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toddler',
            name='ic_number',
            field=models.CharField(default=20, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
