# Generated by Django 5.1.5 on 2025-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_toddler_address_toddler_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
