# Generated by Django 5.1.5 on 2025-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_toddler_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='ic_number',
            field=models.CharField(max_length=20),
        ),
    ]
