# Generated by Django 5.1.5 on 2025-01-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_toddler_ic_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('overdue', 'Overdue')], max_length=20)),
                ('toddler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toddler')),
            ],
        ),
    ]
