# Generated by Django 5.1.5 on 2025-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_adminprofile_parentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher')], default='parent', max_length=10),
        ),
    ]
