# Generated by Django 5.1.5 on 2025-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('admin', 'Admin'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
