# Generated by Django 5.1.5 on 2025-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
