# Generated by Django 5.1.5 on 2025-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_parentprofile_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('admin', 'Admin'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
