# Generated by Django 5.1.5 on 2025-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='toddler',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
