# Generated by Django 5.1.5 on 2025-01-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_toddler_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toddler',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toddler',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='toddler',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toddler',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Day of Week', 'Day of Week'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='toddler',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
