# Generated by Django 5.1.5 on 2025-01-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_toddler_activity_name_toddler_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toddler',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='toddler',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='toddler',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='toddler',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='toddler',
            name='start_time',
        ),
    ]
