# Generated by Django 5.1.5 on 2025-01-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_toddler_activity_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('Day Of Week', 'Day Of Week'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity_name', models.CharField(max_length=255)),
                ('toddler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.toddler')),
            ],
        ),
    ]
