# Generated by Django 5.1.5 on 2025-01-29 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='parent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toddlers', to=settings.AUTH_USER_MODEL),
        ),
    ]
