# Generated by Django 5.1.5 on 2025-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_toddler_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
