# Generated by Django 5.1.5 on 2025-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_toddler_parent_name_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
