# Generated by Django 5.1.5 on 2025-01-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='toddler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.toddler'),
        ),
    ]
