# Generated by Django 5.1.5 on 2025-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_schedule_toddler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='ic_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
