# Generated by Django 5.1.5 on 2025-01-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_toddler_ic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddler',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='toddler',
            name='ic_number',
            field=models.CharField(max_length=20),
        ),
    ]
