# Generated by Django 5.1.5 on 2025-01-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_toddler_full_name_alter_toddler_ic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='toddler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toddler'),
        ),
    ]
