# Generated by Django 5.1.5 on 2025-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_schedule_toddler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('maybank', 'Maybank'), ('cimb', 'CIMB'), ('bank_islam', 'Bank Islam')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('fpx', 'FPX (Bank Transfer)')], default='fpx', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
