# Generated by Django 5.1.5 on 2025-01-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_payment_card_info_alter_payment_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('fpx', 'FPX (Online Banking)'), ('card', 'Credit/Debit Card')], max_length=4),
        ),
    ]
