# Generated by Django 5.1.5 on 2025-01-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_content',
            new_name='feedback_text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='parent',
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipient',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher')], default='admin', max_length=10),
        ),
        migrations.DeleteModel(
            name='FeedbackReply',
        ),
    ]
