# Generated by Django 5.1.5 on 2025-01-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_feedback_date_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
