# Generated by Django 5.1.5 on 2025-01-31 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher')], max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('toddler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toddler')),
            ],
        ),
    ]
