# Generated by Django 5.1.5 on 2025-01-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='recipient',
            field=models.CharField(choices=[('Teacher', 'Teacher')], max_length=20),
        ),
    ]
