# Generated by Django 5.1.5 on 2025-02-03 09:52

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=10)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField(auto_now_add=True)),
                ('toddler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toddler')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='Default Activity Name', max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(default=app.models.get_default_user_profile, limit_choices_to={'user_type__in': ['teacher', 'parent']}, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
                ('toddler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.toddler')),
            ],
        ),
    ]
