# Generated by Django 5.1.5 on 2025-02-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_performancerating_scheduleactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleActivity',
        ),
    ]
