# Generated by Django 5.1.5 on 2025-02-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_scheduleactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
